### ISSUE TITLE
Question: full-screen talks?

### ISSUE THREAD

**Issue by keflavich** [pkgw/htmltalk#1]
I've started making a presentation using the general tools here, but it doesn't scale well when in full-screen mode; the text and figures stay at the same size as in the browser.  I'm also seeing alignment issues, where the centering is fine in the original browser window but is offset as if it were a fixed-left-side-offset when in fullscreen.

Have you encountered and dealt with any of these issues?

**Comment by pkgw** [comment]
Hmmm ... I don't have either of those problems. How are you full-screening? I'm just making my Firefox (or Chrome) windows fullscreen with Alt-F11 or whatever.

I'm not quite sure how I'd diagnose things ... I haven't updated this repo for a little while — maybe something has bitrotted? If you go to https://revealjs.com/ and fullscreen that presentation, do things look right?

**Comment by keflavich** [comment]
Yes, they do, so I suspect it's something with one of the styles I'm using.  I'll investigate further.  Thanks.

**Comment by keflavich** [comment]
The problem was a hard-coded style.  I had made the slides on the slid.es editor, which I'm now abandoning because of their pay-to-export policy, but I might revisit...  anyway, they created lines like this:
```
<div class="sl-block" data-block-type="text" style="width: 806px; left: 77px; top: 189px; height: auto;" data-block-id="151a50162be742f0390e9588549872f7">
```
which I believe are the problem.  `width` should probably (?) be `auto`; left and top should be unspecified.

**Comment by keflavich** [comment]
I was wrong, it's something to do with the parent `<div class="slides">`.  In reveal.js, there is a zoom parameter that gets updated when I change the size of the window.  In my talk, it doesn't...

**Comment by keflavich** [comment]
In the `Reveal.initialize`, you have to set `maxScale: 10` or some number to allow scaling >1; the default is 1.  This is probably just a consequence of my testing on an oversize monitor instead of a projector.

**Comment by pkgw** [comment]
Nice debugging! If you want the (GitHub) credit for the change, feel free to submit a PR, or I can just do it myself.

**Comment by keflavich** [comment]
I'll submit a PR once/if I'm satisfied.  I now have an issue where one figure is off the bottom of the page, and I can't figure out what to tweak to get the margins set up reasonably.  There's a long learning process ahead here...

**Comment by pkgw** [comment]
Cool. Certainly when I got my templates working, I spent a lot of quality time with the Firefox developer tools ... and I'm sure it's the case that my templates interact poorly with some constructs that I just don't use.

**Comment by keflavich** [comment]
I'm using chrome's inspector, which does the same things (I hope).  I don't think it's likely a case of anything you did interacting poorly, but it might be that there's some crap I inherited from slid.es that is.  I'm not entirely sure how safe it is to manually modify styles for individual elements, but I think that's what I need to do to get overlapping figures, etc.

**Comment by keflavich** [comment]
Do you have any further tips on better filling the screen?  I can't make the individual slides fully fill the screen without hacking each individual one, and I haven't figured out what in the CSS is causing the problem.  This is from the chrome inspector highlighting the slide <section> region:

![image](https://user-images.githubusercontent.com/143715/42062899-8a428ac0-7aec-11e8-9b7b-9d3319ffb7bc.png)

Note the whitespace above and below the figure

**Comment by keflavich** [comment]
Nevermind, again this is a revealjs configuration item: set `margin=0` in the reveal.initialize section to remove margins.

**Comment by pkgw** [comment]
Yeah, I find that reveal.js's overall CSS/layout framework is ... quite opaque. There are a few sizes hardcoded in the JS in places too, I think. But anyway, can this issue be closed?

**Comment by keflavich** [comment]
Yeah, I'll close it. But I might ask and answer a few more questions afterward... I doubt I've caught all the corners yet.

**Comment by pkgw** [comment]
I would be impressed if you had caught them all already :-) If you've been taking notes about the roadblocks you've run into, it would be great to get them posted somewhere, somehow, though! Some things like the `slid.es` CSS are gonna be pretty unusual, I think, but I'm sure that other things will be more common. I dunno, could activate the wiki feature for this repo and make a FAQ, or something? Any thoughts?

**Comment by keflavich** [comment]
A wiki would be neat, but for now, I'm too deep into just getting it working for the talk next week to write up anything formally.  This Issue will show up on google eventually anyway, so despite poor organization, some of the key information is out there
